apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      timeField: "@timestamp"
      esVersion: 7.17.10
      maxConcurrentShardRequests: 256
      interval: Daily
    editable: true 