global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'analysis_service'
    static_configs:
      - targets: ['analysis_service:8006']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'catalog_service'
    static_configs:
      - targets: ['catalog_service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'cart_service'
    static_configs:
      - targets: ['cart_service:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'main_service'
    static_configs:
      - targets: ['main_service:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s 